// Spark Services bot
// Auto-detects owners by their "Owners" role, downloads their Discord avatars
// to assets/avatars/, and writes assets/owners-data.js which the website reads.
// No database needed.
//
// Setup:
//   1. npm install
//   2. Copy .env.example to .env and fill it in
//   3. npm start
//
// Commands:
//   /owners sync                    - pull all members with the Owners role + avatars
//   /owners add <member> <server>   - add/update an owner on the public list
//   /owners remove <member>         - remove an owner
//   /owners list                    - show the owners list
//   /server upsert <name> <type> <ram> [owner] - add or update a server
//   /server status <name> <status>  - mark a server online/offline/suspended
//   /server stats                   - show total / online counts
//   /server sync                    - rewrite the data file with the server count

require("dotenv").config();

const { Client, GatewayIntentBits, SlashCommandBuilder, PermissionFlagsBits } = require("discord.js");
const fs = require("fs");
const path = require("path");

const TOKEN = process.env.DISCORD_TOKEN;
const GUILD_ID = process.env.GUILD_ID || null;
const OWNERS_ROLE_ID = process.env.OWNERS_ROLE_ID || null;

if (!TOKEN) {
    console.error("Missing DISCORD_TOKEN. Check bot/.env (see .env.example).");
    process.exit(1);
}

const ASSETS_DIR = path.join(__dirname, "..", "assets");
const AVATAR_DIR = path.join(ASSETS_DIR, "avatars");
const DATA_FILE = path.join(ASSETS_DIR, "owners-data.js");

const client = new Client({ intents: [GatewayIntentBits.Guilds, GatewayIntentBits.GuildMembers] });

// ---------------------------------------------------------------------------
// Local registry of hosted servers. The bot keeps this up to date, then
// /server sync (or a periodic timer) rewrites the data file.
// ---------------------------------------------------------------------------
let servers = [
    // { bot_id: "123456789", owner_id: "111", name: "Example Bot", type: "bot", ram_gb: 2, status: "online" },
];

// Owners currently published to the site: { id, name, server, avatar }
let owners = [];

function ensureDirs() {
    fs.mkdirSync(AVATAR_DIR, { recursive: true });
}

function writeDataFile() {
    const sorted = owners.slice().sort((a, b) => (a.name || "").localeCompare(b.name || ""));
    const payload = {
        owners: sorted,
        servers: {
            total: servers.length,
            online: servers.filter((s) => s.status === "online").length
        }
    };
    const js =
        "/* Generated by the Spark Services bot - do not edit. */\n" +
        "window.SPARK_OWNERS = " + JSON.stringify(payload.owners) + ";\n" +
        "window.SPARK_SERVERS = " + JSON.stringify(payload.servers) + ";\n";
    fs.writeFileSync(DATA_FILE, js, "utf8");
    console.log(`Wrote ${DATA_FILE} - ${payload.owners.length} owner(s), ${payload.servers.online}/${payload.servers.total} server(s) online.`);
}

async function downloadAvatar(userId, url) {
    try {
        const res = await fetch(url);
        if (!res.ok) return null;
        const buf = Buffer.from(await res.arrayBuffer());
        const file = path.join(AVATAR_DIR, userId + ".png");
        fs.writeFileSync(file, buf);
        return "assets/avatars/" + userId + ".png";
    } catch (e) {
        console.error(`Avatar download failed for ${userId}:`, e.message);
        return null;
    }
}

function serverNameFor(ownerId) {
    const s = servers.find((x) => x.owner_id === ownerId);
    return s ? s.name : null;
}

async function roleOwners() {
    if (!OWNERS_ROLE_ID) return [];
    const guild = GUILD_ID ? client.guilds.cache.get(GUILD_ID) : client.guilds.cache.first();
    if (!guild) return [];

    let members;
    try {
        members = await guild.members.fetch();
    } catch (e) {
        console.error("Could not fetch guild members (enable the Server Members intent):", e.message);
        return [];
    }

    const roleMembers = members.filter((m) => m.roles.cache.has(OWNERS_ROLE_ID) && !m.user.bot);
    const result = [];
    for (const m of roleMembers.values()) {
        const avatar = await downloadAvatar(m.id, m.user.displayAvatarURL({ extension: "png", size: 128 }));
        result.push({
            id: m.id,
            name: m.displayName,
            server: serverNameFor(m.id) || m.displayName,
            avatar
        });
    }
    return result;
}

// Rebuild the list purely from the Owners role, then write the file.
async function syncOwnersFromRole() {
    ensureDirs();
    owners = await roleOwners();
    writeDataFile();
    return owners.length;
}

// ---------------------------------------------------------------------------
// Slash commands
// ---------------------------------------------------------------------------
const commands = [
    new SlashCommandBuilder()
        .setName("owners")
        .setDescription("Manage the public owners list")
        .addSubcommand((s) => s.setName("sync").setDescription("Sync all members with the Owners role into the list"))
        .addSubcommand((s) =>
            s
                .setName("add")
                .setDescription("Add or update an owner on the public list")
                .addUserOption((o) => o.setName("member").setDescription("Discord user").setRequired(true))
                .addStringOption((o) => o.setName("server").setDescription("Their server name").setRequired(true))
        )
        .addSubcommand((s) =>
            s
                .setName("remove")
                .setDescription("Remove an owner from the public list")
                .addUserOption((o) => o.setName("member").setDescription("Discord user").setRequired(true))
        )
        .addSubcommand((s) => s.setName("list").setDescription("Show the current owners list")),
    new SlashCommandBuilder()
        .setName("server")
        .setDescription("Manage hosted server stats")
        .addSubcommand((s) =>
            s
                .setName("upsert")
                .setDescription("Add or update a server")
                .addStringOption((o) => o.setName("name").setDescription("Server / bot name").setRequired(true))
                .addStringOption((o) =>
                    o
                        .setName("type")
                        .setDescription("bot or mc")
                        .setRequired(true)
                        .addChoices({ name: "Bot", value: "bot" }, { name: "Minecraft", value: "mc" })
                )
                .addIntegerOption((o) => o.setName("ram").setDescription("RAM in GB").setRequired(true).setMinValue(1))
                .addUserOption((o) => o.setName("owner").setDescription("Owner (Discord user)"))
        )
        .addSubcommand((s) =>
            s
                .setName("status")
                .setDescription("Set a server's status")
                .addStringOption((o) => o.setName("name").setDescription("Server / bot name").setRequired(true))
                .addStringOption((o) =>
                    o
                        .setName("status")
                        .setDescription("online, offline, or suspended")
                        .setRequired(true)
                        .addChoices(
                            { name: "Online", value: "online" },
                            { name: "Offline", value: "offline" },
                            { name: "Suspended", value: "suspended" }
                        )
                )
        )
        .addSubcommand((s) => s.setName("stats").setDescription("Show total / online server counts"))
        .addSubcommand((s) => s.setName("sync").setDescription("Rewrite the data file with the server count")),
];

const OWNER_COMMANDS = ["owners"]; // manage owners list
const ADMIN_COMMANDS = ["server"]; // manage server stats

client.once("ready", async () => {
    console.log(`Logged in as ${client.user.tag}`);

    try {
        if (GUILD_ID) {
            await client.application.commands.set(commands, GUILD_ID);
            console.log("Commands registered in guild", GUILD_ID);
        } else {
            await client.application.commands.set(commands);
            console.log("Commands registered globally");
        }
    } catch (e) {
        console.error("Failed to register commands:", e.message);
    }

    // write the data file periodically so the server count stays fresh
    setInterval(writeDataFile, 5 * 60 * 1000);

    // pull owners from the Owners role on startup, then every 15 minutes
    await syncOwnersFromRole();
    setInterval(syncOwnersFromRole, 15 * 60 * 1000);
});

client.on("interactionCreate", async (interaction) => {
    if (!interaction.isChatInputCommand()) return;

    const commandName = interaction.commandName;
    const isOwner = interaction.member && interaction.member.id === interaction.guild.ownerId;
    const isAdmin = interaction.memberPermissions && interaction.memberPermissions.has(PermissionFlagsBits.Administrator);

    if (OWNER_COMMANDS.includes(commandName) && !(isOwner || isAdmin)) {
        return interaction.reply({ content: "You need Administrator to manage the owners list.", ephemeral: true });
    }
    if (ADMIN_COMMANDS.includes(commandName) && !isAdmin) {
        return interaction.reply({ content: "You need Administrator to manage server stats.", ephemeral: true });
    }

    try {
        if (commandName === "owners") {
            await handleOwners(interaction);
        } else if (commandName === "server") {
            await handleServer(interaction);
        }
    } catch (e) {
        console.error(e);
        if (!interaction.replied) {
            await interaction.reply({ content: "Something went wrong.", ephemeral: true });
        }
    }
});

async function handleOwners(interaction) {
    const sub = interaction.options.getSubcommand();

    if (sub === "sync") {
        await interaction.deferReply();
        const count = await syncOwnersFromRole();
        return interaction.followUp(`Synced ${count} owner(s) from the Owners role.`);
    }

    if (sub === "add") {
        const user = interaction.options.getUser("member");
        const server = interaction.options.getString("server");
        ensureDirs();
        const avatar = await downloadAvatar(user.id, user.displayAvatarURL({ extension: "png", size: 128 }));
        const existing = owners.find((o) => o.id === user.id);
        if (existing) {
            existing.name = user.displayName;
            existing.server = server;
            existing.avatar = avatar || existing.avatar;
        } else {
            owners.push({ id: user.id, name: user.displayName, server, avatar });
        }
        writeDataFile();
        return interaction.reply({ content: `Added ${user} as owner of "${server}". It will appear on the website.` });
    }

    if (sub === "remove") {
        const user = interaction.options.getUser("member");
        const before = owners.length;
        owners = owners.filter((o) => o.id !== user.id);
        if (owners.length === before) {
            return interaction.reply({ content: `${user} is not on the owners list.`, ephemeral: true });
        }
        writeDataFile();
        return interaction.reply({ content: `Removed ${user} from the owners list.` });
    }

    if (sub === "list") {
        if (!owners.length) return interaction.reply({ content: "No owners listed yet." });
        const lines = owners.map((o) => `• ${o.name} — ${o.server}`).join("\n");
        return interaction.reply({ content: `**Owners (${owners.length})**\n${lines}` });
    }
}

async function handleServer(interaction) {
    const sub = interaction.options.getSubcommand();

    if (sub === "upsert") {
        const name = interaction.options.getString("name");
        const type = interaction.options.getString("type");
        const ram = interaction.options.getInteger("ram");
        const owner = interaction.options.getUser("owner");

        let entry = servers.find((s) => s.name === name);
        if (!entry) {
            entry = {
                bot_id: String(Math.random()).slice(2, 20),
                owner_id: owner ? owner.id : (interaction.member ? interaction.member.id : "unknown"),
                name,
                type,
                ram_gb: ram,
                status: "online",
                region: "DE-FRA",
            };
            servers.push(entry);
        } else {
            entry.type = type;
            entry.ram_gb = ram;
            if (owner) entry.owner_id = owner.id;
        }

        writeDataFile();
        return interaction.reply({ content: `Server "${name}" (${type}, ${ram}GB) saved.` });
    }

    if (sub === "status") {
        const name = interaction.options.getString("name");
        const status = interaction.options.getString("status");
        const entry = servers.find((s) => s.name === name);
        if (!entry) return interaction.reply({ content: `No server named "${name}". Use /server upsert first.`, ephemeral: true });
        entry.status = status;
        writeDataFile();
        return interaction.reply({ content: `"${name}" is now **${status}**.` });
    }

    if (sub === "stats") {
        const online = servers.filter((s) => s.status === "online").length;
        return interaction.reply({ content: `**Server stats**\nTotal: ${servers.length}\nOnline: ${online}` });
    }

    if (sub === "sync") {
        writeDataFile();
        return interaction.reply({ content: `Wrote ${servers.length} server(s) to the data file.` });
    }
}

client.login(TOKEN);
